### ISSUE TITLE
Can't clone repo. Filename issue in Windows

### ISSUE THREAD

**Issue by toxydose** [danielmiessler/SecLists#591] opened 2021-04-11 00:43 UTC
![image](https://user-images.githubusercontent.com/20900400/114288350-ac73fb80-9a77-11eb-8dd6-eb32d510edd7.png)

Hi, I have an issue with cloning SecLists repository on Windows machine because of this payload in the filename.

I can propose to store payloads within the file content. And the end user can just copy it's original name and rename this file.

**Comment by g0tmi1k** [comment] 2021-04-11 05:40
Duplicate of #515

May also want to download via ZIP/tar and then extract what you want from the file

**Closed by g0tmi1k** 2021-04-11 05:40 UTC
