### ISSUE TITLE
Missing merged file

### ISSUE THREAD

**Issue by sbts** [danielmiessler/SecLists#116] opened 2017-04-27 14:32 UTC
[Passwords/README](https://github.com/danielmiessler/SecLists/blob/master/Passwords/README) states that a file `merged.txt.tar.gz` should exist.

That file doesn't seem to be in `/passwords`

**Comment by xrobin** [comment] 2017-06-13 09:31
Looks like commit  https://github.com/danielmiessler/SecLists/commit/9b8e66e6421a579dadae38fe3550be3967973f3a.
Is there a way to include a script that would re-generate this file?

**Comment by xrobin** [comment] 2017-06-13 09:33
Actually this is a duplicate of issue #70

**Comment by g0tmi1k** [comment] 2018-03-07 09:49
Duplicate of #172

Fixed in #180

**Closed** 2018-03-20 07:37 UTC
