### ISSUE TITLE
same help plz

### ISSUE THREAD

**Issue by mhhakik** [danielmiessler/SecLists#165] opened 2018-01-05 20:04 UTC
hi 
how can open this file (phpbb-withcount.txt.icloud) !!!

**Comment by lambdacasserole** [comment] 2018-01-06 16:38
Looks like that was committed by accident. Just go back in the version history to before this change was made and you can get it [here](https://github.com/danielmiessler/SecLists/blob/788cdb889c84aec5afd24845cf7202fe65fcab10/Passwords/phpbb-withcount.txt). Suggest closing this one @danielmiessler.

**Comment by g0tmi1k** [comment] 2018-03-07 09:46
Removed in #180.

Duplicate of #166

**Closed** 2018-03-20 07:36 UTC
