### ISSUE TITLE
[Request]: Reduce pack file size: currently almost 650MB = 1/4 of the whole repo

### ISSUE THREAD

**Issue by drwetter** [danielmiessler/SecLists#1105] opened 2024-11-19 10:11 UTC
Hi,

the repo became a bit unhandy :

![image](https://github.com/user-attachments/assets/4cd86bdb-1392-42f7-b337-641047bd5051)

Why is that pack file so big ? And: do you see a possibility shrinking the pack file ? 

Cheers, Dirk

PS: Related maybe: #54 (maybe the first q was going into that direction but then the repo files were discussed which is not my point)

**Comment by ItsIgnacioPortal** [comment] 2024-12-10 23:28
Duplicate of #54

**Closed** 2024-12-20 05:00 UTC
Labels: question
