### ISSUE TITLE
Remove codes 

### ISSUE THREAD

**Issue by Nea80133** [danielmiessler/SecLists#959] opened 2024-01-06 01:05 UTC
https://github.com/danielmiessler/SecLists/blame/dc7f0f98a936e71dc083378ba8a2655132e25d65/Discovery/Web-Content/common.txt#L1427C7-L1427C7 

I did not install any of this on my phone and I want to remove it I cannot figure out how please and thank you you are messing with my job once again I repeat I did not install any of this on my phone I want it removed please for the love of God help me or well I I guess I'll just have to call a lawyer and see your company from infringements on my privacy a wireless tampering so please find me someone that will remove all this out of my phone and make sure that it cannot happen again

**Comment by molangning** [comment] 2024-01-06 09:36
Bro what are you talking about? Just delete the repository if you don't like it
 SecLists isn't even a company so who are you sueing???

**Comment by g0tmi1k** [comment] 2024-02-13 16:01
Hello @Nea80133 .

Im not sure exactly what the issue is, so Im closing it.

Feel free to reply with more detailed information of what the problem/issue is and we can take it from there.

**Closed by g0tmi1k** 2024-02-13 16:01 UTC
